module.exports = {
  content: ["./client/index.html", "./client/src/**/*.{js,jsx,ts,tsx}",
    "./src/**/*.{html,js,ts,jsx,tsx}",
    "app/**/*.{ts,tsx}",
    "components/**/*.{ts,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "app-secondary": "var(--app-secondary)",
        "dark-mode300": "var(--dark-mode300)",
        "dark-mode400": "var(--dark-mode400)",
        "dark-mode700": "var(--dark-mode700)",
        "dark-mode900": "var(--dark-mode900)",
        "dark-modedark-50": "var(--dark-modedark-50)",
        "errorred-400": "var(--errorred-400)",
        "main-2": "var(--main-2)",
        "neutral-100": "var(--neutral-100)",
        "neutral-200": "var(--neutral-200)",
        "neutral-300": "var(--neutral-300)",
        "neutral-400": "var(--neutral-400)",
        "neutral-500": "var(--neutral-500)",
        "neutral-600": "var(--neutral-600)",
        "neutral-900": "var(--neutral-900)",
        "secondary-100": "var(--secondary-100)",
        "secondary-200": "var(--secondary-200)",
        "secondary-300": "var(--secondary-300)",
        "secondary-400": "var(--secondary-400)",
        "secondary-50": "var(--secondary-50)",
        "secondary-500": "var(--secondary-500)",
        "secondary-900": "var(--secondary-900)",
        shadeswhite: "var(--shadeswhite)",
        border: "hsl(var(--border))",
        input: "hsl(var(--input))",
        ring: "hsl(var(--ring))",
        background: "hsl(var(--background))",
        foreground: "hsl(var(--foreground))",
        primary: {
          DEFAULT: "hsl(var(--primary))",
          foreground: "hsl(var(--primary-foreground))",
        },
        secondary: {
          DEFAULT: "hsl(var(--secondary))",
          foreground: "hsl(var(--secondary-foreground))",
        },
        destructive: {
          DEFAULT: "hsl(var(--destructive))",
          foreground: "hsl(var(--destructive-foreground))",
        },
        muted: {
          DEFAULT: "hsl(var(--muted))",
          foreground: "hsl(var(--muted-foreground))",
        },
        accent: {
          DEFAULT: "hsl(var(--accent))",
          foreground: "hsl(var(--accent-foreground))",
        },
        popover: {
          DEFAULT: "hsl(var(--popover))",
          foreground: "hsl(var(--popover-foreground))",
        },
        card: {
          DEFAULT: "hsl(var(--card))",
          foreground: "hsl(var(--card-foreground))",
        },
      },
      fontFamily: {
        "caption-regular": "var(--caption-regular-font-family)",
        "display-01-semi-bold": "var(--display-01-semi-bold-font-family)",
        "display-02-semi-bold": "var(--display-02-semi-bold-font-family)",
        "heading-h1-semi-bold": "var(--heading-h1-semi-bold-font-family)",
        "heading-h1-small-semi-bold":
          "var(--heading-h1-small-semi-bold-font-family)",
        "heading-h3-small-semi-bold":
          "var(--heading-h3-small-semi-bold-font-family)",
        "heading-h4-semi-bold": "var(--heading-h4-semi-bold-font-family)",
        "heading-h5-semi-bold": "var(--heading-h5-semi-bold-font-family)",
        "heading-h6-semi-bold": "var(--heading-h6-semi-bold-font-family)",
        "heading-h6-small-semi-bold":
          "var(--heading-h6-small-semi-bold-font-family)",
        "paragraph-p1-regular": "var(--paragraph-p1-regular-font-family)",
        "paragraph-p1-semi-bold": "var(--paragraph-p1-semi-bold-font-family)",
        "paragraph-p2-regular": "var(--paragraph-p2-regular-font-family)",
        "paragraph-p2-semi-bold": "var(--paragraph-p2-semi-bold-font-family)",
        "paragraph-p3-regular": "var(--paragraph-p3-regular-font-family)",
        "paragraph-p3-semi-bold": "var(--paragraph-p3-semi-bold-font-family)",
        "subheading-regular": "var(--subheading-regular-font-family)",
        "subheading-semi-bold": "var(--subheading-semi-bold-font-family)",
        sans: [
          "ui-sans-serif",
          "system-ui",
          "sans-serif",
          '"Apple Color Emoji"',
          '"Segoe UI Emoji"',
          '"Segoe UI Symbol"',
          '"Noto Color Emoji"',
        ],
      },
      borderRadius: {
        lg: "var(--radius)",
        md: "calc(var(--radius) - 2px)",
        sm: "calc(var(--radius) - 4px)",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
    container: { center: true, padding: "2rem", screens: { "2xl": "1400px" } },
  },
  plugins: [require("tailwindcss-animate"), require("@tailwindcss/typography")],
  darkMode: ["class"],
};
